### ISSUE TITLE
Pass Redux Store as last parameter to state change handler

### ISSUE THREAD

**Issue by ghost** [franjohn21/redux-on-state-change#15]
This will help to support multiple instances of the redux store. Rematch JS recently released a version that supports multiple instances. https://rematch.netlify.app/#/quick-start. I tried to submit a PR but the repo is locked.
Very minor change:
```
export default fn => store => next => action => {
  const prevState = store.getState();
  const result = next(action);
  const nextState = store.getState();
  fn(prevState, nextState, action, store);
  return result;
};
```

**Comment by franjohn21** [comment]
Done!

>  I tried to submit a PR but the repo is locked.

Hmm can you show me a screenshot of what you're seeing? Not sure why it'd be locked
